# Generated by Django 5.2.10 on 2026-01-29 16:17

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('plataforma_certificacao', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminAuditorProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matricula', models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='Matrícula')),
                ('departamento', models.CharField(blank=True, max_length=100, null=True, verbose_name='Departamento')),
                ('pode_auditar_produtores', models.BooleanField(default=True, verbose_name='Pode Auditar Produtores')),
                ('pode_verificar_empresas', models.BooleanField(default=True, verbose_name='Pode Verificar Empresas')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('data_atualizacao', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('ultimo_acesso', models.DateTimeField(blank=True, null=True, verbose_name='Último Acesso')),
            ],
            options={
                'verbose_name': 'Perfil de Admin/Auditor',
                'verbose_name_plural': 'Perfis de Admins/Auditores',
                'db_table': 'AdminAuditorProfile',
            },
        ),
        migrations.CreateModel(
            name='EmpresaProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cnpj', models.CharField(blank=True, max_length=18, null=True, unique=True, verbose_name='CNPJ')),
                ('razao_social', models.CharField(blank=True, max_length=255, null=True, verbose_name='Razão Social')),
                ('nome_fantasia', models.CharField(blank=True, max_length=255, null=True, verbose_name='Nome Fantasia')),
                ('inscricao_estadual', models.CharField(blank=True, max_length=20, null=True, verbose_name='Inscrição Estadual')),
                ('documento_contrato_social', models.FileField(blank=True, null=True, upload_to='empresas/documentos/', verbose_name='Contrato Social')),
                ('documento_cnpj', models.FileField(blank=True, null=True, upload_to='empresas/documentos/', verbose_name='Comprovante de CNPJ')),
                ('documento_alvara', models.FileField(blank=True, null=True, upload_to='empresas/documentos/', verbose_name='Alvará de Funcionamento')),
                ('status_verificacao', models.CharField(choices=[('pendente', 'Pendente de Verificação'), ('verificado', 'Verificado e Aprovado'), ('rejeitado', 'Rejeitado'), ('suspenso', 'Suspenso')], default='pendente', max_length=10, verbose_name='Status de Verificação')),
                ('data_verificacao', models.DateTimeField(blank=True, null=True, verbose_name='Data da Verificação')),
                ('observacoes_verificacao', models.TextField(blank=True, null=True, verbose_name='Observações do Auditor')),
                ('endereco_comercial', models.CharField(blank=True, max_length=255, null=True, verbose_name='Endereço Comercial')),
                ('cidade', models.CharField(blank=True, max_length=100, null=True, verbose_name='Cidade')),
                ('estado', models.CharField(blank=True, max_length=2, null=True, verbose_name='Estado (UF)')),
                ('cep', models.CharField(blank=True, max_length=9, null=True, verbose_name='CEP')),
                ('telefone_comercial', models.CharField(blank=True, max_length=20, null=True, verbose_name='Telefone Comercial')),
                ('site', models.URLField(blank=True, null=True, verbose_name='Website')),
                ('descricao_empresa', models.TextField(blank=True, null=True, verbose_name='Descrição da Empresa')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='perfis/empresas/', verbose_name='Logo')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('data_atualizacao', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
            ],
            options={
                'verbose_name': 'Perfil de Empresa',
                'verbose_name_plural': 'Perfis de Empresas',
                'db_table': 'EmpresaProfile',
                'ordering': ['-data_criacao'],
            },
        ),
        migrations.CreateModel(
            name='ProdutorProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cpf', models.CharField(blank=True, max_length=14, null=True, unique=True, verbose_name='CPF')),
                ('bio', models.TextField(blank=True, null=True, verbose_name='Biografia')),
                ('foto_perfil', models.ImageField(blank=True, null=True, upload_to='perfis/produtores/', verbose_name='Foto de Perfil')),
                ('cidade', models.CharField(blank=True, max_length=100, null=True, verbose_name='Cidade')),
                ('estado', models.CharField(blank=True, max_length=2, null=True, verbose_name='Estado (UF)')),
                ('cep', models.CharField(blank=True, max_length=9, null=True, verbose_name='CEP')),
                ('whatsapp', models.CharField(blank=True, max_length=20, null=True, verbose_name='WhatsApp')),
                ('instagram', models.CharField(blank=True, max_length=100, null=True, verbose_name='Instagram')),
                ('facebook', models.CharField(blank=True, max_length=100, null=True, verbose_name='Facebook')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('data_atualizacao', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
            ],
            options={
                'verbose_name': 'Perfil de Produtor',
                'verbose_name_plural': 'Perfis de Produtores',
                'db_table': 'ProdutorProfile',
            },
        ),
        migrations.RemoveField(
            model_name='empresa',
            name='usuario',
        ),
        migrations.RemoveField(
            model_name='empresaprodutor',
            name='usuario',
        ),
        migrations.RemoveField(
            model_name='produtor',
            name='usuario',
        ),
        migrations.AlterModelOptions(
            name='certificacoes',
            options={'ordering': ['-data_envio'], 'verbose_name': 'Certificação', 'verbose_name_plural': 'Certificações'},
        ),
        migrations.AlterModelOptions(
            name='produtos',
            options={'ordering': ['-data_criacao'], 'verbose_name': 'Produto', 'verbose_name_plural': 'Produtos'},
        ),
        migrations.AlterModelOptions(
            name='usuariobase',
            options={'ordering': ['-data_criacao'], 'verbose_name': 'Usuário', 'verbose_name_plural': 'Usuários'},
        ),
        migrations.AddField(
            model_name='produtos',
            name='data_atualizacao',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Atualizado em'),
        ),
        migrations.AddField(
            model_name='produtos',
            name='data_criacao',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Criado em'),
        ),
        migrations.AlterField(
            model_name='carrinho',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='carrinhos', to=settings.AUTH_USER_MODEL, verbose_name='Usuário'),
        ),
        migrations.AlterField(
            model_name='certificacoes',
            name='admin_responsavel',
            field=models.ForeignKey(blank=True, db_column='admin_responsavel_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='certificacoes_analisadas', to=settings.AUTH_USER_MODEL, verbose_name='Auditor Responsável'),
        ),
        migrations.AlterField(
            model_name='certificacoes',
            name='data_envio',
            field=models.DateField(blank=True, null=True, verbose_name='Data de Envio'),
        ),
        migrations.AlterField(
            model_name='certificacoes',
            name='data_resposta',
            field=models.DateField(blank=True, null=True, verbose_name='Data de Resposta'),
        ),
        migrations.AlterField(
            model_name='certificacoes',
            name='documento',
            field=models.FileField(max_length=255, upload_to='certificacoes/', verbose_name='Documento Principal'),
        ),
        migrations.AlterField(
            model_name='certificacoes',
            name='documento_2',
            field=models.FileField(blank=True, max_length=255, null=True, upload_to='certificacoes/', verbose_name='Documento Adicional 1'),
        ),
        migrations.AlterField(
            model_name='certificacoes',
            name='documento_3',
            field=models.FileField(blank=True, max_length=255, null=True, upload_to='certificacoes/', verbose_name='Documento Adicional 2'),
        ),
        migrations.AlterField(
            model_name='certificacoes',
            name='observacoes_admin',
            field=models.TextField(blank=True, null=True, verbose_name='Observações do Auditor'),
        ),
        migrations.AlterField(
            model_name='certificacoes',
            name='produto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificacoes', to='plataforma_certificacao.produtos', verbose_name='Produto'),
        ),
        migrations.AlterField(
            model_name='certificacoes',
            name='status_certificacao',
            field=models.CharField(blank=True, choices=[('pendente', 'Pendente de Análise'), ('aprovado', 'Aprovado'), ('reprovado', 'Reprovado')], default='pendente', max_length=9, null=True, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='certificacoes',
            name='texto_autodeclaracao',
            field=models.TextField(blank=True, null=True, verbose_name='Texto da Autodeclaração'),
        ),
        migrations.AlterField(
            model_name='itemcarrinho',
            name='carrinho',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='plataforma_certificacao.carrinho', verbose_name='Carrinho'),
        ),
        migrations.AlterField(
            model_name='itemcarrinho',
            name='produto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plataforma_certificacao.produtos', verbose_name='Produto'),
        ),
        migrations.AlterField(
            model_name='itempedido',
            name='pedido',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='plataforma_certificacao.pedido', verbose_name='Pedido'),
        ),
        migrations.AlterField(
            model_name='itempedido',
            name='produto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plataforma_certificacao.produtos', verbose_name='Produto'),
        ),
        migrations.AlterField(
            model_name='marketplace',
            name='produto',
            field=models.ForeignKey(db_column='produto_id', on_delete=django.db.models.deletion.CASCADE, related_name='anuncios', to='plataforma_certificacao.produtos'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pedidos', to=settings.AUTH_USER_MODEL, verbose_name='Usuário'),
        ),
        migrations.AlterField(
            model_name='produtos',
            name='descricao',
            field=models.TextField(blank=True, null=True, verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='produtos',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to='produtos/', verbose_name='Imagem'),
        ),
        migrations.AlterField(
            model_name='produtos',
            name='nome',
            field=models.CharField(max_length=100, verbose_name='Nome do Produto'),
        ),
        migrations.AlterField(
            model_name='produtos',
            name='preco',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Preço Unitário'),
        ),
        migrations.AlterField(
            model_name='produtos',
            name='status_estoque',
            field=models.CharField(blank=True, choices=[('disponivel', 'Disponível'), ('esgotado', 'Esgotado')], default='disponivel', max_length=10, null=True, verbose_name='Status de Estoque'),
        ),
        migrations.AlterField(
            model_name='produtos',
            name='usuario',
            field=models.ForeignKey(db_column='usuario_id', on_delete=django.db.models.deletion.CASCADE, related_name='produtos', to=settings.AUTH_USER_MODEL, verbose_name='Produtor'),
        ),
        migrations.AlterField(
            model_name='usuariobase',
            name='email',
            field=models.EmailField(max_length=100, unique=True, validators=[django.core.validators.EmailValidator()], verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='usuariobase',
            name='is_superuser',
            field=models.BooleanField(default=False, verbose_name='Superusuário'),
        ),
        migrations.AddIndex(
            model_name='certificacoes',
            index=models.Index(fields=['status_certificacao'], name='Certificaco_status__d09906_idx'),
        ),
        migrations.AddIndex(
            model_name='certificacoes',
            index=models.Index(fields=['data_envio'], name='Certificaco_data_en_4e6901_idx'),
        ),
        migrations.AddIndex(
            model_name='certificacoes',
            index=models.Index(fields=['produto', 'status_certificacao'], name='Certificaco_produto_23b504_idx'),
        ),
        migrations.AddIndex(
            model_name='produtos',
            index=models.Index(fields=['usuario'], name='Produtos_usuario_2273d0_idx'),
        ),
        migrations.AddIndex(
            model_name='produtos',
            index=models.Index(fields=['status_estoque'], name='Produtos_status__2766e3_idx'),
        ),
        migrations.AddIndex(
            model_name='usuariobase',
            index=models.Index(fields=['email'], name='UsuarioBase_email_747f6b_idx'),
        ),
        migrations.AddIndex(
            model_name='usuariobase',
            index=models.Index(fields=['tipo', 'is_active'], name='UsuarioBase_tipo_997953_idx'),
        ),
        migrations.AddIndex(
            model_name='usuariobase',
            index=models.Index(fields=['data_criacao'], name='UsuarioBase_data_cr_5ba7e3_idx'),
        ),
        migrations.AddField(
            model_name='adminauditorprofile',
            name='usuario',
            field=models.OneToOneField(limit_choices_to={'tipo': 'admin'}, on_delete=django.db.models.deletion.CASCADE, related_name='admin_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='empresaprofile',
            name='admin_responsavel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='empresas_verificadas', to=settings.AUTH_USER_MODEL, verbose_name='Auditor Responsável'),
        ),
        migrations.AddField(
            model_name='empresaprofile',
            name='usuario',
            field=models.OneToOneField(limit_choices_to={'tipo': 'empresa'}, on_delete=django.db.models.deletion.CASCADE, related_name='empresa_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='produtorprofile',
            name='usuario',
            field=models.OneToOneField(limit_choices_to={'tipo': 'produtor'}, on_delete=django.db.models.deletion.CASCADE, related_name='produtor_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Empresa',
        ),
        migrations.DeleteModel(
            name='EmpresaProdutor',
        ),
        migrations.DeleteModel(
            name='Produtor',
        ),
        migrations.AddIndex(
            model_name='empresaprofile',
            index=models.Index(fields=['cnpj'], name='EmpresaProf_cnpj_55dfff_idx'),
        ),
        migrations.AddIndex(
            model_name='empresaprofile',
            index=models.Index(fields=['status_verificacao'], name='EmpresaProf_status__8da03b_idx'),
        ),
    ]
