# Generated by Django 6.0.1 on 2026-01-26 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plataforma_certificacao', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='tipo_usuario',
            field=models.CharField(choices=[('produtor', 'Produtor'), ('empresa', 'Comprador'), ('auditor', 'Auditor')], default='produtor', max_length=20),
        ),
        migrations.AlterField(
            model_name='perfilempresa',
            name='cnpj',
            field=models.CharField(max_length=14, unique=True),
        ),
        migrations.AlterField(
            model_name='perfilproduto',
            name='cpf',
            field=models.CharField(max_length=11, unique=True),
        ),
    ]
