# Generated by Django 6.0 on 2026-01-15 20:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plataforma_certificacao', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='certificacoes',
            options={},
        ),
        migrations.AlterModelOptions(
            name='marketplace',
            options={},
        ),
        migrations.AlterModelOptions(
            name='produtos',
            options={},
        ),
        migrations.AlterModelOptions(
            name='usuarios',
            options={},
        ),
    ]
