# Generated by Django 6.0.1 on 2026-01-24 20:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plataforma_certificacao', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificacoes',
            name='admin_responsavel',
            field=models.ForeignKey(blank=True, db_column='admin_responsavel_id', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='plataforma_certificacao.usuarios'),
        ),
        migrations.AlterField(
            model_name='certificacoes',
            name='produto',
            field=models.ForeignKey(db_column='produto_id', default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='plataforma_certificacao.produtos'),
        ),
        migrations.AlterField(
            model_name='certificacoes',
            name='status_certificacao',
            field=models.CharField(blank=True, choices=[('pendente', 'Pendente'), ('aprovado', 'Aprovado'), ('reprovado', 'Reprovado')], default='pendente', max_length=9, null=True),
        ),
        migrations.AlterField(
            model_name='marketplace',
            name='produto',
            field=models.ForeignKey(db_column='produto_id', default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='plataforma_certificacao.produtos'),
        ),
        migrations.AlterField(
            model_name='produtos',
            name='status_estoque',
            field=models.CharField(blank=True, choices=[('disponivel', 'Disponível'), ('esgotado', 'Esgotado')], default='disponivel', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='produtos',
            name='usuario',
            field=models.ForeignKey(db_column='usuario_id', default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='plataforma_certificacao.usuarios'),
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='tipo',
            field=models.CharField(choices=[('produtor', 'Produtor'), ('empresa', 'Empresa'), ('admin', 'Administrador')], max_length=8),
        ),
    ]
