# Generated by Django 6.0.1 on 2026-01-26 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plataforma_certificacao', '0002_alter_customuser_tipo_usuario_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfilproduto',
            name='cpf',
            field=models.CharField(max_length=14, unique=True),
        ),
    ]
