# Generated by Django 6.0.1 on 2026-01-16 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plataforma_certificacao', '0002_alter_certificacoes_options_and_more'),
        ('plataforma_certificacao', '0002_alter_usuarios_options'),
    ]

    operations = [
    ]
