# Generated by Django 6.0.1 on 2026-01-24 23:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plataforma_certificacao', '0002_alter_certificacoes_admin_responsavel_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UsuariosLegado',
            fields=[
                ('id_usuario', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100, unique=True)),
                ('telefone', models.CharField(blank=True, max_length=20, null=True)),
                ('endereco', models.CharField(max_length=100)),
                ('senha', models.CharField(max_length=100)),
                ('tipo', models.CharField(choices=[('produtor', 'Produtor'), ('empresa', 'Empresa'), ('admin', 'Admin')], max_length=8)),
                ('cpf', models.CharField(blank=True, max_length=14, null=True)),
                ('cnpj', models.CharField(blank=True, max_length=18, null=True)),
                ('matricula', models.CharField(blank=True, max_length=12, null=True)),
            ],
            options={
                'verbose_name': 'Usuário (Legado)',
                'verbose_name_plural': 'Usuários (Legado)',
                'db_table': 'Usuarios',
                'managed': False,
            },
        ),
        migrations.AlterModelOptions(
            name='certificacoes',
            options={'verbose_name': 'Certificação', 'verbose_name_plural': 'Certificações'},
        ),
        migrations.AlterModelOptions(
            name='marketplace',
            options={'verbose_name': 'Anúncio Marketplace', 'verbose_name_plural': 'Anúncios Marketplace'},
        ),
        migrations.AlterModelOptions(
            name='produtos',
            options={'verbose_name': 'Produto', 'verbose_name_plural': 'Produtos'},
        ),
        migrations.AlterField(
            model_name='certificacoes',
            name='produto',
            field=models.ForeignKey(db_column='produto_id', on_delete=django.db.models.deletion.DO_NOTHING, to='plataforma_certificacao.produtos'),
        ),
        migrations.AlterField(
            model_name='marketplace',
            name='produto',
            field=models.ForeignKey(db_column='produto_id', on_delete=django.db.models.deletion.DO_NOTHING, to='plataforma_certificacao.produtos'),
        ),
        migrations.CreateModel(
            name='UsuarioBase',
            fields=[
                ('id_usuario', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(blank=True, max_length=100, null=True)),
                ('email', models.CharField(blank=True, max_length=100, null=True)),
                ('tipo', models.CharField(choices=[('produtor', 'Produtor'), ('empresa', 'Empresa'), ('admin', 'Administrador')], default='produtor', max_length=8)),
                ('telefone', models.CharField(blank=True, max_length=20, null=True)),
                ('endereco', models.CharField(blank=True, max_length=255, null=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='usuario_base', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Usuário',
                'verbose_name_plural': 'Usuários',
                'db_table': 'UsuarioBase',
            },
        ),
        migrations.CreateModel(
            name='Produtor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cpf', models.CharField(blank=True, max_length=14, null=True, unique=True)),
                ('data_criacao', models.DateTimeField(auto_now_add=True, null=True)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='produtor_profile', to='plataforma_certificacao.usuariobase')),
            ],
            options={
                'verbose_name': 'Produtor',
                'verbose_name_plural': 'Produtores',
                'db_table': 'Produtores',
            },
        ),
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cnpj', models.CharField(blank=True, max_length=18, null=True, unique=True)),
                ('razao_social', models.CharField(blank=True, max_length=255, null=True)),
                ('data_criacao', models.DateTimeField(auto_now_add=True, null=True)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='empresa_profile', to='plataforma_certificacao.usuariobase')),
            ],
            options={
                'verbose_name': 'Empresa',
                'verbose_name_plural': 'Empresas',
                'db_table': 'Empresas',
            },
        ),
        migrations.AlterField(
            model_name='certificacoes',
            name='admin_responsavel',
            field=models.ForeignKey(blank=True, db_column='admin_responsavel_id', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='plataforma_certificacao.usuariobase'),
        ),
        migrations.AlterField(
            model_name='produtos',
            name='usuario',
            field=models.ForeignKey(db_column='usuario_id', on_delete=django.db.models.deletion.DO_NOTHING, to='plataforma_certificacao.usuariobase'),
        ),
        migrations.DeleteModel(
            name='Usuarios',
        ),
    ]
