# Generated by Django 5.2.10 on 2026-01-29 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plataforma_certificacao', '0002_adminauditorprofile_empresaprofile_produtorprofile_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empresaprofile',
            name='cnpj',
            field=models.CharField(blank=True, max_length=18, null=True, verbose_name='CNPJ'),
        ),
    ]
