# Generated by Django 6.0.1 on 2026-01-16 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plataforma_certificacao', '0003_merge_20260116_1245'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='certificacoes',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='marketplace',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='produtos',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='usuarios',
            options={'managed': False},
        ),
    ]
