# Generated by Django 6.0.1 on 2026-01-26 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plataforma_certificacao', '0003_alter_perfilproduto_cpf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfilproduto',
            name='bio',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='perfilproduto',
            name='cpf',
            field=models.CharField(max_length=11, unique=True),
        ),
    ]
