# Generated by Django 6.0.1 on 2026-01-16 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plataforma_certificacao', '0004_alter_certificacoes_options_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='certificacoes',
            table='Certificacoes',
        ),
        migrations.AlterModelTable(
            name='marketplace',
            table='Marketplace',
        ),
        migrations.AlterModelTable(
            name='produtos',
            table='Produtos',
        ),
        migrations.AlterModelTable(
            name='usuarios',
            table='Usuarios',
        ),
    ]
