# Generated by Django 6.0.1 on 2026-01-25 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plataforma_certificacao', '0004_create_security_groups'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificacoes',
            name='documento_2',
            field=models.FileField(blank=True, max_length=255, null=True, upload_to='certificacoes/'),
        ),
        migrations.AddField(
            model_name='certificacoes',
            name='documento_3',
            field=models.FileField(blank=True, max_length=255, null=True, upload_to='certificacoes/'),
        ),
        migrations.AddField(
            model_name='certificacoes',
            name='observacoes_admin',
            field=models.TextField(blank=True, help_text='Observações do auditor', null=True),
        ),
        migrations.AddField(
            model_name='empresa',
            name='cep',
            field=models.CharField(blank=True, max_length=9, null=True),
        ),
        migrations.AddField(
            model_name='empresa',
            name='cidade',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='empresa',
            name='data_atualizacao',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='empresa',
            name='data_verificacao',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='empresa',
            name='descricao_empresa',
            field=models.TextField(blank=True, help_text='Descrição da empresa', null=True),
        ),
        migrations.AddField(
            model_name='empresa',
            name='documento_alvara',
            field=models.FileField(blank=True, help_text='Alvará de Funcionamento', null=True, upload_to='empresas/documentos/'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='documento_cnpj',
            field=models.FileField(blank=True, help_text='Comprovante de CNPJ', null=True, upload_to='empresas/documentos/'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='documento_contrato_social',
            field=models.FileField(blank=True, help_text='Contrato Social ou Estatuto', null=True, upload_to='empresas/documentos/'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='endereco_comercial',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='empresa',
            name='estado',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='empresa',
            name='inscricao_estadual',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='empresa',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='perfis/empresas/'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='nome_fantasia',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='empresa',
            name='observacoes_verificacao',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='empresa',
            name='site',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='empresa',
            name='status_verificacao',
            field=models.CharField(choices=[('pendente', 'Pendente'), ('verificado', 'Verificado'), ('rejeitado', 'Rejeitado')], default='pendente', max_length=10),
        ),
        migrations.AddField(
            model_name='empresa',
            name='telefone_comercial',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='produtor',
            name='bio',
            field=models.TextField(blank=True, help_text='Biografia do produtor', null=True),
        ),
        migrations.AddField(
            model_name='produtor',
            name='cep',
            field=models.CharField(blank=True, max_length=9, null=True),
        ),
        migrations.AddField(
            model_name='produtor',
            name='cidade',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='produtor',
            name='data_atualizacao',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='produtor',
            name='estado',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='produtor',
            name='facebook',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='produtor',
            name='foto_perfil',
            field=models.ImageField(blank=True, null=True, upload_to='perfis/produtores/'),
        ),
        migrations.AddField(
            model_name='produtor',
            name='instagram',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='produtor',
            name='whatsapp',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
