# Generated by Django 6.0.1 on 2026-01-16 17:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plataforma_certificacao', '0006_add_arquivo_autodeclaracao'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='certificacoes',
            options={},
        ),
        migrations.AlterModelOptions(
            name='marketplace',
            options={},
        ),
        migrations.AlterModelOptions(
            name='produtos',
            options={},
        ),
        migrations.AlterModelOptions(
            name='usuarios',
            options={},
        ),
    ]
