"""
Django settings for amazonia_marketing project.

Generated by 'django-admin startproject' using Django 6.0.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-koaer_$o0-(pfr*btq(uxxq5#*46#p1wdj6kw3_-oheq+$!7nn'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.sites',                   # Necessário para django-allauth
    'allauth',
    'allauth.account',
    'allauth.socialaccount',
    'allauth.socialaccount.providers.google', # Provedor Google para django-allauth
    'plataforma_certificacao',
]

AUTHETICATION_BACKENDS = [
    'django.contrib.auth.backends.ModelBackend', # Backend padrão do Django
    'allauth.account.auth_backends.AuthenticationBackend', # Backend do allauth
]

SITE_ID = 1  # Necessário para django-allauth
LOGIN_REDIRECT_URL = '/'  # Redireciona para a página inicial após login

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'allauth.account.middleware.AccountMiddleware',  # Middleware do allauth
]

ROOT_URLCONF = 'amazonia_marketing.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'amazonia_marketing.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

#Iniciando ligação do django com o banco de dados 
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',  # Engine padrão do Django para MySQL
        'NAME': 'amazonia_marketing',          # Nome exato do banco que criamos
        'USER': 'django_user',                 # Seu usuário do MySQL
        'PASSWORD': 'django123',               # Senha
        'HOST': '127.0.0.1',                   # Localhost
        'PORT': '3306',                        # Porta padrão
        'OPTIONS': {
            'init_command': "SET sql_mode='STRICT_TRANS_TABLES'",
            'charset': 'utf8mb4',
        },
    }
}

# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'

# Configurando arquivos de media

# Endereço virtual na internet 
# Exemplo: navegador solicita: http://site.com/media/foto.jpg
MEDIA_URL = '/media/'

# Endereço físico do meu computador - > fotos serão guardadas na pasta media
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# Configurações de Upload de Arquivos
FILE_UPLOAD_MAX_MEMORY_SIZE = 5242880  # 5MB em bytes

# Extensões permitidas para upload
ALLOWED_UPLOAD_EXTENSIONS = ['pdf', 'doc', 'docx', 'jpg', 'jpeg', 'png']

# MIME types permitidos para upload
ALLOWED_UPLOAD_MIME_TYPES = [
    'application/pdf',
    'application/msword',
    'application/vnd.openxmlformats-officedocument.wordprocessingml.document',
    'image/jpeg',
    'image/png',
]

# ============================================
# Configuração de Autenticação Customizada
# ============================================

# Modelo de usuário customizado (LOGIN COM EMAIL)
AUTH_USER_MODEL = 'plataforma_certificacao.CustomUser'

# ============================================
# Configurações do django-allauth
# ============================================

# ID do site (necessário para allauth)
SITE_ID = 1

# Backends de autenticação
AUTHENTICATION_BACKENDS = [
    # Backend padrão do Django (para CustomUser)
    'django.contrib.auth.backends.ModelBackend',
    
    # Backend do allauth para social login
    'allauth.account.auth_backends.AuthenticationBackend',
]

# Configurações de autenticação
LOGIN_REDIRECT_URL = '/'  # Para onde redirecionar após login
ACCOUNT_LOGOUT_REDIRECT_URL = '/'
ACCOUNT_SIGNUP_FIELDS = ['email*', 'password1*', 'password2*']
ACCOUNT_LOGIN_METHODS = {'email'}
ACCOUNT_EMAIL_VERIFICATION = 'optional'  # 'mandatory' para obrigar verificação

# Configurações do provedor Google
SOCIALACCOUNT_PROVIDERS = {
    'google': {
        'SCOPE': [
            'profile',
            'email',
        ],
        'AUTH_PARAMS': {
            'access_type': 'online',
            'prompt': 'select_account',  # força o Google a mostrar o seletor de contas
        },
        # Nota: As credenciais devem ser configuradas no Django Admin
        # em Social Applications, não aqui no código
    }
}

# Adapter customizado para mapear dados do Google para UsuarioBase
SOCIALACCOUNT_ADAPTER = 'plataforma_certificacao.adapters.CustomSocialAccountAdapter'
SOCIALACCOUNT_QUERY_EMAIL = True

# Pular tela de sign in e ir direto para o login com a conta social
SOCIALACCOUNT_LOGIN_ON_GET = True

