"""
Django settings for backend_amazonia project.

Generated by 'django-admin startproject' using Django 6.0.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-koaer_$o0-(pfr*btq(uxxq5#*46#p1wdj6kw3_-oheq+$!7nn'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'core',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'backend_amazonia.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'backend_amazonia.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

#Iniciando ligação do django com o banco de dados

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',  # FORÇAR A USAR MYSQL
        'NAME': 'amazonia_marketing',          # Nome exato do banco que criamos
<<<<<<< Updated upstream:Códigos/Backend/backend_amazonia/backend_amazonia/settings.py
<<<<<<< Updated upstream:Códigos/Backend/backend_amazonia/backend_amazonia/settings.py
<<<<<<< Updated upstream:Códigos/Backend/backend_amazonia/backend_amazonia/settings.py
        'USER': 'root',                        # Seu usuário do MySQL
        'PASSWORD': 'admin',                    # Sua senha (confirme se é essa mesma)
=======
        'USER': 'django_user',                 # Seu usuário do MySQL
        'PASSWORD': 'django123',               # Sua senha do MySQL
>>>>>>> Stashed changes:amazonia_marketing/amazonia_marketing/settings.py
=======
        'USER': 'django_user',                 # Seu usuário do MySQL
        'PASSWORD': 'django123',               # Sua senha do MySQL
>>>>>>> Stashed changes:amazonia_marketing/amazonia_marketing/settings.py
=======
        'USER': 'django_user',                 # Seu usuário do MySQL
        'PASSWORD': 'django123',               # Sua senha do MySQL
>>>>>>> Stashed changes:amazonia_marketing/amazonia_marketing/settings.py
        'HOST': '127.0.0.1',                   # Localhost
        'PORT': '3306',                        # Porta padrão do MySQL
        'OPTIONS': {
            'init_command': "SET sql_mode='STRICT_TRANS_TABLES'",
        },
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'

# Media files (Upload de arquivos do usuário)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

import os
MEDIA_URL = 'media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# Configurações de upload
FILE_UPLOAD_MAX_MEMORY_SIZE = 5242880  # 5MB
DATA_UPLOAD_MAX_MEMORY_SIZE = 5242880  # 5MB
DATA_UPLOAD_MAX_NUMBER_FIELDS = 1000

# Tipos de arquivo permitidos
ALLOWED_UPLOAD_EXTENSIONS = ['pdf', 'doc', 'docx', 'jpg', 'jpeg', 'png']
ALLOWED_UPLOAD_MIME_TYPES = [
    'application/pdf',
    'application/msword',
    'application/vnd.openxmlformats-officedocument.wordprocessingml.document',
    'image/jpeg',
    'image/png',
]

# Configuração de armazenamento de mídia
DEFAULT_FILE_STORAGE = 'django.core.files.storage.FileSystemStorage'
