# Generated by Django 6.0 on 2026-01-08 18:20

import django.db.models.deletion
from django.db import migrations, models
import django.db.models.deletion
import django.core.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
<<<<<<< Updated upstream:PVD/core/migrations/0001_initial.py
            name='Produtos',
            fields=[
                ('id_produto', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=100)),
                ('categoria', models.CharField(max_length=100)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('preco', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('status_estoque', models.CharField(blank=True, max_length=10, null=True)),
            ],
            options={
                'db_table': 'Produtos',
            },
        ),
        migrations.CreateModel(
=======
>>>>>>> Stashed changes:amazonia_marketing/plataforma_certificacao/migrations/0001_initial.py
            name='Usuarios',
            fields=[
                ('id_usuario', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100, unique=True)),
                ('telefone', models.CharField(blank=True, max_length=20, null=True)),
                ('endereco', models.CharField(max_length=100)),
                ('senha', models.CharField(max_length=100)),
                ('tipo', models.CharField(max_length=8)),
                ('cpf', models.CharField(blank=True, max_length=14, null=True)),
                ('cnpj', models.CharField(blank=True, max_length=18, null=True)),
                ('matricula', models.CharField(blank=True, max_length=12, null=True)),
            ],
            options={
<<<<<<< Updated upstream:PVD/core/migrations/0001_initial.py
                'db_table': 'Usuarios',
=======
                'db_table': 'usuarios',
            },
        ),
        migrations.CreateModel(
            name='Produtos',
            fields=[
                ('id_produto', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=100)),
                ('categoria', models.CharField(max_length=100)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('preco', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('status_estoque', models.CharField(blank=True, max_length=10, null=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='plataforma_certificacao.usuarios')),
            ],
            options={
                'db_table': 'produtos',
>>>>>>> Stashed changes:amazonia_marketing/plataforma_certificacao/migrations/0001_initial.py
            },
        ),
        migrations.CreateModel(
            name='Marketplace',
            fields=[
                ('id_anuncio', models.AutoField(primary_key=True, serialize=False)),
                ('plataforma', models.CharField(max_length=80)),
                ('conteudo_gerado', models.TextField(blank=True, null=True)),
                ('data_geracao', models.DateField(blank=True, null=True)),
<<<<<<< Updated upstream:PVD/core/migrations/0001_initial.py
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.produtos')),
            ],
            options={
                'db_table': 'Marketplace',
            },
        ),
        migrations.AddField(
            model_name='produtos',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.usuarios'),
        ),
=======
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='plataforma_certificacao.produtos')),
            ],
            options={
                'db_table': 'marketplace',
            },
        ),
>>>>>>> Stashed changes:amazonia_marketing/plataforma_certificacao/migrations/0001_initial.py
        migrations.CreateModel(
            name='Certificacoes',
            fields=[
                ('id_certificacao', models.AutoField(primary_key=True, serialize=False)),
                ('texto_autodeclaracao', models.TextField(blank=True, null=True)),
                ('documento', models.CharField(max_length=255)),
<<<<<<< Updated upstream:PVD/core/migrations/0001_initial.py
                ('status_certificacao', models.CharField(blank=True, max_length=9, null=True)),
                ('data_envio', models.DateField(blank=True, null=True)),
                ('data_resposta', models.DateField(blank=True, null=True)),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.produtos')),
                ('admin_responsavel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.usuarios')),
            ],
            options={
                'db_table': 'Certificacoes',
=======
                ('arquivo_autodeclaracao', models.FileField(blank=True, help_text='Arquivo de autodeclaração (máximo 5MB). Formatos aceitos: PDF, DOC, DOCX, JPG, PNG', null=True, upload_to='autodeclaracoes/%Y/%m/%d/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'doc', 'docx', 'jpg', 'jpeg', 'png'])])),
                ('status_certificacao', models.CharField(blank=True, max_length=9, null=True)),
                ('data_envio', models.DateField(blank=True, null=True)),
                ('data_resposta', models.DateField(blank=True, null=True)),
                ('admin_responsavel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='plataforma_certificacao.usuarios')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='plataforma_certificacao.produtos')),
            ],
            options={
                'db_table': 'certificacoes',
>>>>>>> Stashed changes:amazonia_marketing/plataforma_certificacao/migrations/0001_initial.py
            },
        ),
    ]
