# Generated by Django 6.0.1 on 2026-01-15 02:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plataforma_certificacao', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usuarios',
            options={},
        ),
    ]
